---
title: "ssb_R"
author: "Heike"
date: '2022-05-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(openxlsx)
library(tidyverse)
library(dplyr)
library(janitor)
library(norgeo)
library(httr)
library(rjstat)

```

## download ssb-data via link

```{r}
#ssb_data = read.csv("https://data.ssb.no/api/v0/dataset/list.csv?lang=en")
#ssb_data = ssb_data %>% row_to_names(row_number = 1)
```

## Example from website ssb 

(https://www.ssb.no/api/pxwebapi/api-eksempler-pa-kode/eurostat-api-enkelt-r-eksempel-med-json-stat)

```{r, echo=FALSE}
options(encoding="UTF-8")


# bruk rjstat  pakken for JSON-Stat

# REST request HCPI laget med Eurostat query builder http://ec.europa.eu/eurostat/web/json-and-unicode-web-services  
url <- "http://ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/en/prc_hicp_mv12r?precision=1&geo=DK&geo=NO&geo=SE&geo=DE&geo=UK&sinceTimePeriod=2012M01&coicop=CP00&unit=RCH_MV12MAVR"
d.tmp<-GET(url)

# hent innhold fra d.tmp som text, ved å bruke fromJSONstat i rjstat pakken 
sbtable <- fromJSONstat(content(d.tmp, "text"))

# hent bare datasettet fra sbtable
ds <- sbtable[[1]]

# vis datasettet
ds

```

(https://www.ssb.no/api/pxwebapi/api-eksempler-pa-kode/r-eksempel-med-pxwebapi-og-http-post)

```{r}
options(encoding="UTF-8")
library(httr)

# henter rjstat bibliotek for behandling av JSON-stat
library(rjstat)
url <- "https://data.ssb.no/api/v0/no/table/09190"

# spørring fra konsoll - kan være på en linje
data <- '
{"query":
[{"code":"Makrost","selection":{"filter":"item","values": ["koh.nrpriv","koo.nroff","bif.nr83_6","makrok.nrianv","eks.nrtot","imp.nrtot","bnpb.nr23_9","bnpb.nr23_9fn","bnpb.nr23oljsj"]}},{"code":"ContentsCode","selection":{"filter":"item","values":["Priser","Faste","PriserSesJust"]}},{"code":"Tid","selection":{"filter":"top","values":["8"]}}],
"response":{"format":"json-stat2"}}
'
d.tmp <- POST(url , body = data, encode = "json", verbose())

# Henter ut innholdet fra d.tmp som tekst deretter bearbeides av fromJSONstat
sbtabell <- fromJSONstat(content(d.tmp, "text"))

# Viser datasettet
sbtabell

# med versjon 1 av json-stat vil sbtabell være en liste. Slik hentes kun datasettet fra sbtabell
#ds <- sbtabell[[1]]
#ds


# Samme, men med bruk av biblioteket PxWebApiData og url over
library (PxWebApiData)
ApiData(url, 
        ContentsCode = c("Priser","Faste","PriserSesJust"), 
        Makrost = c("koh.nrpriv","koo.nroff","bif.nr83_6","makrok.nrianv","eks.nrtot","imp.nrtot","bnpb.nr23_9","bnpb.nr23_9fn","bnpb.nr23oljsj"),
        Tid = 8i,
        returnDataSet = 1)
```

